let res = {
  modelType: "meta.elements_group",
  aquery: [
    {
      select: [],
      dataSource: "ele_join_creative",
      filters: [
        {
          reFun: "AND",
          rules: [
            {
              field: "install_date",
              fieldId: "install_date",
              opFun: "BETWEEN",
              params: ["2021-08-02", "2025-08-02"],
            },
            {
              field: "creative_start_date",
              fieldId: "creative_start_date",
              opFun: "BETWEEN",
              params: ["2021-08-02", "2025-08-02"],
            },
            {
              field: "os",
              fieldId: "os",
              opFun: "EQ",
              params: ["iOS"],
            },
            {
              field: "app_name",
              fieldId: "app_name",
              opFun: "EQ",
              params: ["Solitaire Clash Infinite"],
            },
            {
              field: "country",
              fieldId: "country",
              opFun: "EQ",
              params: ["US"],
            },
            {
              field: "media_source",
              fieldId: "media_source",
              opFun: "EQ",
              params: ["applovin"],
            },
            {
              field: "cost",
              fieldId: "cost",
              opFun: "LTE",
              params: ["1000000"],
            },
          ],
        },
      ],
    },
    {
      select: [],
      dataSource:
        "production_dataai.ads_math.fact_avia_customize_material_elements_creator",
      filters: [
        {
          reFun: "AND",
          rules: [
            {
              field: "creator",
              fieldId: "creator",
              opFun: "EQ",
              params: [
                "MLH",
                "CBW",
                "ZYL",
                "LY",
                "XMH",
                "LMH",
                "WLY",
                "GY",
                "JJL",
                "ZLW",
                "WC",
                "YLG",
                "RY",
                "WQY",
                "SP",
                "MSL",
                "HL",
                "YYR",
                "JZH",
                "WLN",
                "WSN",
                "ZWT",
                "WDN",
                "ZM",
                "DFF",
                "YJ",
                "LBW",
                "YXQ",
                "WXS",
                "WLM",
                "HSB",
                "LJX",
                "JWJ",
                "ONE",
                "YXH",
                "XDS",
                "Unknown",
                "GHL",
                "DH",
                "WMY",
              ],
            },
          ],
        },
      ],
    },
  ],
  orders: [],
  groupBy: "theme", //[scene_description,theme,character_relationships,character_identity]
}
